package com.gourmetoven.gourmetapp.util;

public class TestConstants {

    private TestConstants() {
    }

    public static final String ingredientsExpected = "[{\"ingredientId\":101,\"ingredientName\":\"Cheese\"},{\"ingredientId\":102,\"ingredientName\":\"Paprika\"},{\"ingredientId\":103,\"ingredientName\":\"Salami\"},{\"ingredientId\":104,\"ingredientName\":\"Pineapple\"},{\"ingredientId\":105,\"ingredientName\":\"Potato\"},{\"ingredientId\":106,\"ingredientName\":\"Salt\"},{\"ingredientId\":107,\"ingredientName\":\"Salmon\"},{\"ingredientId\":108,\"ingredientName\":\"Onion\"},{\"ingredientId\":109,\"ingredientName\":\"Garlic\"},{\"ingredientId\":110,\"ingredientName\":\"Chicken\"},{\"ingredientId\":111,\"ingredientName\":\"Egg\"},{\"ingredientId\":112,\"ingredientName\":\"Mustard\"},{\"ingredientId\":113,\"ingredientName\":\"Lettuce\"}]";

    public static final String recipesExpected_All_Deafult = "[{\"recipeId\":101,\"name\":\"Pineapple Pizza\",\"servings\":4,\"dishType\":\"vegetarian\",\"creationType\":\"default\",\"user\":\"default\",\"ingredients\":[{\"ingredientId\":104,\"ingredientName\":\"Pineapple\"},{\"ingredientId\":101,\"ingredientName\":\"Cheese\"},{\"ingredientId\":106,\"ingredientName\":\"Salt\"}],\"instructions\":[\"No Garlic\",\"No Paprika\",\"Lots of Pineapple\"]},{\"recipeId\":102,\"name\":\"Salami Pizza\",\"servings\":2,\"dishType\":\"vegetarian\",\"creationType\":\"default\",\"user\":\"default\",\"ingredients\":[{\"ingredientId\":101,\"ingredientName\":\"Cheese\"},{\"ingredientId\":103,\"ingredientName\":\"Salami\"},{\"ingredientId\":105,\"ingredientName\":\"Potato\"}],\"instructions\":[]},{\"recipeId\":103,\"name\":\"Potato Pizza\",\"servings\":2,\"dishType\":\"vegetarian\",\"creationType\":\"default\",\"user\":\"default\",\"ingredients\":[{\"ingredientId\":112,\"ingredientName\":\"Mustard\"},{\"ingredientId\":109,\"ingredientName\":\"Garlic\"},{\"ingredientId\":105,\"ingredientName\":\"Potato\"}],\"instructions\":[]},{\"recipeId\":104,\"name\":\"Omlette\",\"servings\":5,\"dishType\":\"non-vegetarian\",\"creationType\":\"default\",\"user\":\"default\",\"ingredients\":[{\"ingredientId\":111,\"ingredientName\":\"Egg\"},{\"ingredientId\":109,\"ingredientName\":\"Garlic\"},{\"ingredientId\":106,\"ingredientName\":\"Salt\"}],\"instructions\":[\"Lots of Garlic\",\"No Paprika\"]},{\"recipeId\":106,\"name\":\"Spanish Omlette\",\"servings\":2,\"dishType\":\"non-vegetarian\",\"creationType\":\"default\",\"user\":\"user1\",\"ingredients\":[{\"ingredientId\":111,\"ingredientName\":\"Egg\"},{\"ingredientId\":101,\"ingredientName\":\"Cheese\"}],\"instructions\":[\"Two eggs\"]},{\"recipeId\":107,\"name\":\"Potato stew\",\"servings\":1,\"dishType\":\"vegetarian\",\"creationType\":\"default\",\"user\":\"user1\",\"ingredients\":[{\"ingredientId\":105,\"ingredientName\":\"Potato\"},{\"ingredientId\":106,\"ingredientName\":\"Salt\"}],\"instructions\":[\"Lots of potatos\"]}]";
    public static final String recipesExpectedForType_Vegetarian = "[{\"recipeId\":101,\"name\":\"Pineapple Pizza\",\"servings\":4,\"dishType\":\"vegetarian\",\"creationType\":\"default\",\"user\":\"default\",\"ingredients\":[{\"ingredientId\":104,\"ingredientName\":\"Pineapple\"},{\"ingredientId\":101,\"ingredientName\":\"Cheese\"},{\"ingredientId\":106,\"ingredientName\":\"Salt\"}],\"instructions\":[\"No Garlic\",\"No Paprika\",\"Lots of Pineapple\"]},{\"recipeId\":102,\"name\":\"Salami Pizza\",\"servings\":2,\"dishType\":\"vegetarian\",\"creationType\":\"default\",\"user\":\"default\",\"ingredients\":[{\"ingredientId\":101,\"ingredientName\":\"Cheese\"},{\"ingredientId\":103,\"ingredientName\":\"Salami\"},{\"ingredientId\":105,\"ingredientName\":\"Potato\"}],\"instructions\":[]},{\"recipeId\":103,\"name\":\"Potato Pizza\",\"servings\":2,\"dishType\":\"vegetarian\",\"creationType\":\"default\",\"user\":\"default\",\"ingredients\":[{\"ingredientId\":112,\"ingredientName\":\"Mustard\"},{\"ingredientId\":109,\"ingredientName\":\"Garlic\"},{\"ingredientId\":105,\"ingredientName\":\"Potato\"}],\"instructions\":[]},{\"recipeId\":107,\"name\":\"Potato stew\",\"servings\":1,\"dishType\":\"vegetarian\",\"creationType\":\"default\",\"user\":\"user1\",\"ingredients\":[{\"ingredientId\":105,\"ingredientName\":\"Potato\"},{\"ingredientId\":106,\"ingredientName\":\"Salt\"}],\"instructions\":[\"Lots of potatos\"]}]";

    public static final String recipeExpected_4_ALL_ExcludeSalami_Include_Instruction="[{\"recipeId\":101,\"name\":\"Pineapple Pizza\",\"servings\":4,\"dishType\":\"vegetarian\",\"creationType\":\"default\",\"user\":\"default\",\"ingredients\":[{\"ingredientId\":104,\"ingredientName\":\"Pineapple\"},{\"ingredientId\":101,\"ingredientName\":\"Cheese\"},{\"ingredientId\":106,\"ingredientName\":\"Salt\"}],\"instructions\":[\"No Garlic\",\"No Paprika\",\"Lots of Pineapple\"]}]";


    public static final String searchResult_2_nonVeg_Salami = "[{\"recipeId\":106,\"name\":\"Spanish Omlette\",\"servings\":2,\"dishType\":\"non-vegetarian\",\"creationType\":\"default\",\"user\":\"user1\",\"ingredients\":[{\"ingredientId\":111,\"ingredientName\":\"Egg\"},{\"ingredientId\":101,\"ingredientName\":\"Cheese\"}],\"instructions\":[\"Two eggs\"]}]";

    public static final String
            recipeCreateResult = "{\"recipeId\":1,\"name\":\"sambar\",\"servings\":2,\"dishType\":\"vegetarian\",\"creationType\":\"Custom\",\"user\":\"user1\",\"ingredients\":[{\"ingredientId\":101,\"ingredientName\":\"Cheese\"},{\"ingredientId\":102,\"ingredientName\":\"Paprika\"}],\"instructions\":[]}";

    public static final String recipeUpdateResult = "{\"recipeId\":2,\"name\":\"Sambar\",\"servings\":6,\"dishType\":\"vegetarian\",\"creationType\":\"Custom\",\"user\":\"user1\",\"ingredients\":[{\"ingredientId\":101,\"ingredientName\":\"Cheese\"},{\"ingredientId\":102,\"ingredientName\":\"Paprika\"},{\"ingredientId\":103,\"ingredientName\":\"Salami\"}],\"instructions\":[]}";
}